import type { NextPage } from 'next'
import { Fragment } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Card, { CardHeader, CardContent, CardFooter } from "../components/Card";
import Table from "../components/Table";
import Chip, {ChipList} from "../components/Chip";
import Button from '../components/Button';
import {Icon} from "../components/Icon";

const Home: NextPage = () => {
  return (
    <Fragment>
      <div className={'page'} data-theme={'dark'}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={'wrapper'}>
          <main>
            <Card
                type={'primary'}
                flex={true}
            >
              <CardHeader heading={'Hello there'} />
              <CardContent>
                Card content goes here
                <div>
                  <Button color={'indigo'} iconType={'arrow-right-double'}>Indigo button</Button>
                  <Button color={'green'} iconType={'arrow-right-double'}>Green button</Button>
                  <Button color={'green'} disabled>Disabled button</Button>
                </div>
                <ChipList>
                  <Chip type={'tertiary'} solid>Chippy</Chip>
                  <Chip type={'secondary'} solid>Chippy</Chip>
                  <Chip type={'primary'}>Chippy</Chip>
                </ChipList>
                <Icon color={'pink'} />
              </CardContent>
              <CardFooter>Footer go brrr</CardFooter>
            </Card>

            {/*<Table*/}
            {/*    headings={['Test', 'Moose', 'Geese too']}*/}
            {/*    data={d}*/}
            {/*/>*/}
          </main>
        </div>
      </div>
    </Fragment>
  )
}

const d = [
  [ 'one', 'two', 'three' ],
  [ 'nine', 'nine', 'six' ],
  [ 'four', 'seven', 'eight' ],
]


export default Home
